export const optionHelp = {
  invalidRecord: "invalid records",
  undefinedField: "fields not found in the field schedule",
  deprecatedField: "report deprecated fields",
  nonrepeatableField: "repetition of non-repeatable fields",
  missingField: "required fields missing from a record",
  invalidIndicator: "field not matching expected validation definition",
  invalidFieldValue: "invalid flat field values",
  invalidSubfield: "invalid subfields (subsumes all subfield errors)",
  undefinedSubfield: "subfields not found in the subfield schedule",
  deprecatedSubfield: "report deprecated subfields",
  nonrepeatableSubfield: "repetition of non-repeatable subfields",
  missingSubfield: "required subfields missing from a field",
  invalidSubfieldValue: "invalid subfield values",
  patternMismatch: "values not matching an expected pattern",
  invalidPosition: "values not matching expected positions",
  recordTypes: "support record types",
  invalidFlag: "value is not a concatenation of flags",
  undefinedCode: "values not found in an expected codelist",
  undefinedCodelist: "non-resolveable codelist references",
  countRecord: "expected number of records not met",
  countField: "expected number of fields not met", 
  countSubfield: "expected number of subfields not met",
//  externalRule: "violation of external rules",
}

export const optionDefault = {
  invalidRecord: true,
  undefinedField: true,
  deprecatedField: true,
  nonrepeatableField: true,
  missingField: true,
  invalidIndicator: true,
  invalidFieldValue: true,
  invalidSubfield: true,
  undefinedSubfield: true,
  deprecatedSubfield: true,
  nonrepeatableSubfield: true,
  missingSubfield: true,
  invalidSubfieldValue: true,
  patternMismatch: true,
  invalidPosition: true,
  recordTypes: true,
  invalidFlag: true,
  undefinedCode: true,
  undefinedCodelist: false,
  countRecord: false,
  countField: false, 
  countSubfield: false,
//  externalRule: false,
}
